"""Add active attr in user.

Revision ID: 46600521f028
Revises: 654c7b4a369a
Create Date: 2026-01-01 23:27:04.211068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46600521f028'
down_revision = '654c7b4a369a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
